# Generated by Django 4.0.3 on 2022-04-02 11:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhotoFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_favorite', to=settings.AUTH_USER_MODEL)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='webapp.photo')),
            ],
            options={
                'verbose_name': 'Избранное фото',
                'verbose_name_plural': 'Избранные фото',
                'db_table': 'photo_favorite',
            },
        ),
        migrations.CreateModel(
            name='AlbumFavorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='webapp.album')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_favorite', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Избранный альбом',
                'verbose_name_plural': 'Избранные альбомы',
                'db_table': 'album_favorite',
            },
        ),
    ]
